title: "Hugo Stellar"
paginate: 8
relativeURLs: true

theme:
- stellar

markup:
  _merge: deep

params:
  author: Stellar
  avatar: /avatar.png
  logo: /logo.svg

  description:
  - "subtitle"
  - "subsubtitle"

  notice:
  - "notice"
  - "support `markdown` syntax"

  copyright: "place copyright here"

  tencentUrl: true
  autoInvert: true

  social:
  - name: "hugo"
    url: "https://gohugo.io/"
    logo: "/img/social/hugo.svg"
  - name: "github"
    url: "https://github.com/"
    logo: "/img/social/github.svg"
  - name: "bilibili"
    url: "https://space.bilibili.com/"
    logo: "/img/social/bilibili.svg"

menus:
  main:
  - name: "博客"
    weight: 1
    url: "/"
    params:
      tabs:
      - name: "所有文章"
        url: "/"
      - name: "分类"
        url: "/categories/"
      - name: "标签"
        url: "/tags/"
      - name: "归档"
        url: "/archives/"
  - name: "文档"
    weight: 2
    url: "/docs/"
    params:
      tabs:
      - name: "所有文档"
        url: "/docs/"
  - name: "搜索"
    weight: 3
    url: "/search/"
    params:
      tabs:
      - name: "博客搜索"
        url: "/search/?sec=posts"
      - name: "文档搜索"
        url: "/search/?sec=docs"
  - name: "关于"
    weight: 4
    url: "/about/"
    params:
      tabs:
      - name: "About Hugo"
        url: "/about/#about-hugo"
